# Generated by Django 4.2.4 on 2023-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_person_groups_alter_person_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
