# Generated by Django 4.2.4 on 2023-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_person_private_key_person_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
